Null=''
True=true
False=false
TheAnswerToLifeTheUniverseAndEverything=42
FrancToEuro=6.55957
String='The "good", the '\''bad'\'', and Bob-Wan Kenobi'
List=(\
	'one'\
	2\
	'Free'\
)
Dictionary[One]='un'
Dictionary[Two]='deux'
Dictionary[Three]='trois'
Map0=(\
	'one'\
	'un'\
)
MapDucksDisney=(\
	'Donald'\
	'Huey'\
)
MapDucks[Warner]='Daffy'
Map1[Rabbit]='Bugs'
