null=''
true=true
false=false
theAnswerToLifeTheUniverseAndEverything=42
francToEuro=6.55957
string='The "good", the '\''bad'\'', and Bob-Wan Kenobi'
list=(\
	'one'\
	2\
	'Free'\
)
dictionary[one]='un'
dictionary[two]='deux'
dictionary[three]='trois'
map0=(\
	'one'\
	'un'\
)
mapDucksDisney=(\
	'Donald'\
	'Huey'\
)
mapDucks[warner]='Daffy'
map1[rabbit]='Bugs'
