null=''
true=true
false=false
the_answer_to_life_the_universe_and_everything=42
franc_to_euro=6.55957
string='The "good", the '\''bad'\'', and Bob-Wan Kenobi'
list=(\
	'one'\
	2\
	'Free'\
)
dictionary[one]='un'
dictionary[two]='deux'
dictionary[three]='trois'
map_0=(\
	'one'\
	'un'\
)
map_ducks_disney=(\
	'Donald'\
	'Huey'\
)
map_ducks[warner]='Daffy'
map_1[rabbit]='Bugs'
